runtime: nodejs
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "22"
service: default
env: flex
instance_class: F1
entrypoint: npm run start
handlers:
  - url: '.*'
    script: auto
    secure: always
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2